/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import view.myapp.LoginMain;
import dao.DatabaseUtils;
import model.Employee;
import model.EmployeeSkill;
import model.SkillType;

/**
 *
 * @author Yuzana Zaw Zaw
 */
public class AddEmployeeSkill extends javax.swing.JFrame implements
		ItemListener {

	/**
	 * Creates new form AddEmployeeSkill
	 */

	String username;
	Employee empl = new Employee();
	ResultSet rest = null;
	DatabaseUtils connection = null;
	SkillType skillType = new SkillType();
	String[] columnNames = { "Employee Id", "Employee Name", "Skill Type",
			"Skill Level" };
	DefaultTableModel model = new DefaultTableModel();
	// Variables declaration - do not modify
	private javax.swing.JPanel addButton;
	private javax.swing.JPanel addEmployeeSkill;
	private javax.swing.JLabel addEmployeeSkillLbl;
	private javax.swing.JLabel addLbl;
	private javax.swing.JPanel checkRecruiterDetails;
	private javax.swing.JLabel checkRecruiterLbl;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JTable jTable;
	private keeptoo.KGradientPanel kGradientPanel1;
	private javax.swing.JPanel logOutButton;
	private javax.swing.JLabel logoutLbl;
	private javax.swing.JPanel settingsButton;
	private javax.swing.JLabel settingsLbl;
	private javax.swing.JPanel subMainPanel;
	private javax.swing.JLabel title;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JPanel updateEmployeeButton;
	private javax.swing.JLabel updateEmployeeProfile;
	private javax.swing.JTextField addEmployeeId;
	private javax.swing.JPanel xpanel;
	private javax.swing.JPanel ypanel;

	// End of variables declaration
	public AddEmployeeSkill() {
		initComponents();
		loadEmployeeSkills();
	}

	public AddEmployeeSkill(String username) {
		this.username = username;
		initComponents();
		loadEmployeeSkills();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		kGradientPanel1 = new keeptoo.KGradientPanel();
		jPanel2 = new javax.swing.JPanel();
		xpanel = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		ypanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		subMainPanel = new javax.swing.JPanel();
		jSeparator3 = new javax.swing.JSeparator();
		titleLbl = new javax.swing.JLabel();
		updateEmployeeButton = new javax.swing.JPanel();
		updateEmployeeProfile = new javax.swing.JLabel();
		checkRecruiterDetails = new javax.swing.JPanel();
		checkRecruiterLbl = new javax.swing.JLabel();
		addEmployeeSkill = new javax.swing.JPanel();
		addEmployeeSkillLbl = new javax.swing.JLabel();
		settingsButton = new javax.swing.JPanel();
		settingsLbl = new javax.swing.JLabel();
		logOutButton = new javax.swing.JPanel();
		logoutLbl = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		addButton = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		addLbl = new javax.swing.JLabel();
		title = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		addEmployeeId = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox2 = new javax.swing.JComboBox<>();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		kGradientPanel1.setkEndColor(new java.awt.Color(102, 0, 153));
		kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
		kGradientPanel1.setMaximumSize(new java.awt.Dimension(2147483647,
				2147483647));
		kGradientPanel1.setMinimumSize(new java.awt.Dimension(1060, 270));
		kGradientPanel1.setPreferredSize(new java.awt.Dimension(1060, 646));
		kGradientPanel1.setLayout(null);

		jPanel2.setOpaque(false);

		xpanel.setBackground(new java.awt.Color(0, 0, 51));
		xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xpanelMouseClicked(evt);
			}

		});

		jLabel11.setBackground(new java.awt.Color(0, 0, 51));
		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("X");

		javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(
				xpanel);
		xpanel.setLayout(xpanelLayout);
		xpanelLayout.setHorizontalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xpanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel11)
						.addContainerGap()));
		xpanelLayout.setVerticalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel11, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		ypanel.setBackground(new java.awt.Color(0, 0, 51));
		ypanel.setForeground(new java.awt.Color(0, 0, 51));
		ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ypanelMouseClicked(evt);
			}
		});

		jLabel12.setBackground(new java.awt.Color(0, 0, 0));
		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("-");

		javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(
				ypanel);
		ypanel.setLayout(ypanelLayout);
		ypanelLayout.setHorizontalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel12)
						.addContainerGap()));
		ypanelLayout.setVerticalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout.createSequentialGroup()
						.addGap(0, 1, Short.MAX_VALUE).addComponent(jLabel12)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout
						.createSequentialGroup()
						.addGap(0, 13, Short.MAX_VALUE)
						.addComponent(ypanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(xpanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		kGradientPanel1.add(jPanel2);
		jPanel2.setBounds(840, 10, 80, 30);

		subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

		titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(204, 204, 204));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("RM SYS");
		titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		updateEmployeeButton.setBackground(new java.awt.Color(0, 0, 51));
		updateEmployeeButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						updateEmployeeButtonMouseClicked(evt);
					}

				});
		updateEmployeeButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		updateEmployeeProfile
				.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		updateEmployeeProfile.setForeground(new java.awt.Color(240, 240, 240));
		updateEmployeeProfile
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		updateEmployeeProfile.setText("Update Profile");
		updateEmployeeButton.add(updateEmployeeProfile,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		checkRecruiterDetails.setBackground(new java.awt.Color(0, 0, 51));
		checkRecruiterDetails
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						checkRecruiterDetailsMouseClicked(evt);
					}

				});
		checkRecruiterDetails
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		checkRecruiterLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		checkRecruiterLbl.setForeground(new java.awt.Color(240, 240, 240));
		checkRecruiterLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		checkRecruiterLbl.setText("Check Recruiter Detail");
		checkRecruiterDetails.add(checkRecruiterLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320,
						30));

		addEmployeeSkill.setBackground(new java.awt.Color(0, 0, 51));
		addEmployeeSkill.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addEmployeeSkillMouseClicked(evt);
			}

		});
		addEmployeeSkill
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		addEmployeeSkillLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		addEmployeeSkillLbl.setForeground(new java.awt.Color(240, 240, 240));
		addEmployeeSkillLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		addEmployeeSkillLbl.setText("Add Employee Skill");
		addEmployeeSkill.add(addEmployeeSkillLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 310,
						30));

		settingsButton.setBackground(new java.awt.Color(0, 0, 51));
		settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				settingsButtonMouseClicked(evt);
			}

		});
		settingsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		settingsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		settingsLbl.setForeground(new java.awt.Color(240, 240, 240));
		settingsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		settingsLbl.setText("Settings");
		settingsButton.add(settingsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		logOutButton.setBackground(new java.awt.Color(0, 0, 51));
		logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logOutButtonMouseClicked(evt);
			}

		});
		logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
		logoutLbl.setText("Log Out");
		logOutButton.add(logoutLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(
				subMainPanel);
		subMainPanel.setLayout(subMainPanelLayout);
		subMainPanelLayout
				.setHorizontalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								settingsButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								logOutButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								subMainPanelLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												checkRecruiterDetails,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												addEmployeeSkill,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												331,
																												Short.MAX_VALUE)
																										.addComponent(
																												updateEmployeeButton,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))))
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addGap(46,
																				46,
																				46)
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								titleLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								257,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jSeparator3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								268,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		subMainPanelLayout
				.setVerticalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(titleLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(129, 129, 129)
										.addComponent(
												updateEmployeeButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												checkRecruiterDetails,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addEmployeeSkill,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												settingsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												138, Short.MAX_VALUE)
										.addComponent(
												logOutButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(66, 66, 66)));

		kGradientPanel1.add(subMainPanel);
		subMainPanel.setBounds(0, 0, 343, 650);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setForeground(new java.awt.Color(204, 204, 204));
		jPanel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(102, 102, 102));
		jLabel19.setText("Employee Id");

		jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel30.setForeground(new java.awt.Color(102, 102, 102));
		jLabel30.setText("Employee Skill ");

		addButton.setBackground(new java.awt.Color(0, 0, 51));
		addButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addButtonMouseClicked(evt);
			}

		});
		addButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(204, 204, 204));
		jLabel10.setText("EMAIL");
		addButton.add(jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1,
						-1));

		addLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		addLbl.setForeground(new java.awt.Color(204, 204, 204));
		addLbl.setText("Add");
		addButton.add(addLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1,
						-1));

		title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title.setText("Employee Skill");

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(102, 102, 102));
		jLabel4.setText("Skill Level");

		String emplId = empl.getEmployeeByUserName(username);

		addEmployeeId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		addEmployeeId.setForeground(new java.awt.Color(102, 102, 102));
		addEmployeeId.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		addEmployeeId.setText(emplId);
		addEmployeeId.setEditable(false);

		DatabaseUtils conn = new DatabaseUtils();
		conn.OpenConnection();
		String sql = "Select * from skill_type";
		ResultSet rst = conn.GetData(sql);

		try {
			while (rst.next()) {
				String name = rst.getString("description");
				if (name.equals("")) {
					jComboBox1.addItem("");

					jComboBox1.setVisible(true);
				} else {
					jComboBox1.addItem(rst.getString("description"));
					System.out.println(rst.getString("description"));

					jComboBox1.setVisible(true);
				}
			}
			jComboBox1.addItem("NEW SKILL TYPE");
			conn.CloseConnection();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		jComboBox1.addItemListener(this);
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Basic", "Entry", "Advance" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel30,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel19,
																								javax.swing.GroupLayout.Alignment.LEADING))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								addEmployeeId,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								288,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jComboBox1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												146,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addComponent(
																								title,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								245,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jComboBox2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								146,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addContainerGap(
																				47,
																				Short.MAX_VALUE))))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(116, 116, 116)
										.addComponent(
												addButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(title)
										.addGap(18, 18, 18)
										.addComponent(jLabel19)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												addEmployeeId,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel30)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel4)
										.addGap(12, 12, 12)
										.addComponent(
												jComboBox2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												addButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(10, Short.MAX_VALUE)));

		kGradientPanel1.add(jPanel1);
		jPanel1.setBounds(420, 20, 400, 270);
		model.setColumnIdentifiers(columnNames);
		jTable.setForeground(new java.awt.Color(106, 13, 173));
		jTable.setModel(model);
		jTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
		jTable.setFillsViewportHeight(true);
		jTable.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				processTableClick();
			}
		});

		jScrollPane1.setViewportView(jTable);

		kGradientPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(370, 300, 500, 330);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 956,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(288, 288, 288)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 640,
								Short.MAX_VALUE).addContainerGap()));

		setSize(new java.awt.Dimension(961, 646));
		setLocationRelativeTo(null);
	}

	// Adding table header
	public void loadEmployeeSkills() {
		Employee employee = new Employee();
		EmployeeSkill emplSkill = new EmployeeSkill();
		int employee_id = employee.getEmployeeIdByUserName(username);
		String name = employee.getEmployeeName(username);
		List<ArrayList<EmployeeSkill>> skillLists = emplSkill
				.getEmployeeSkillById(employee_id);
		String data[][] = new String[skillLists.size()][4];
		//System.out.println("ROWS"+skillLists.size());
		if (skillLists != null) {
			//model.setColumnIdentifiers(columnNames);
			int i=0;
			for(ArrayList<EmployeeSkill> skills:skillLists){
				for (EmployeeSkill skill : skills) {
					SkillType skillType=new SkillType();
					String emplSkillTypeName = skillType.getSkillTypeNameById(skill.getSkillTypeId());
					model.addRow(new Object[] { employee_id, name,
							emplSkillTypeName, skill.getSkillLevel() });
									
					data[i][0] = employee_id + "";
			        data[i][1] = name;
			        data[i][2] = emplSkillTypeName;
			        data[i][3] = skill.getSkillLevel();
			        System.out.println(data);
			        i++;
			    }
			}
			model=new DefaultTableModel(data,columnNames);
			jTable.setModel(model);
		}
	}

	private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setState(AddEmployeeSkill.ICONIFIED);
	}

	private void updateEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		UpdateEmployeeHome av = new UpdateEmployeeHome(username);
		this.setVisible(false);
		av.setVisible(true);
	}

	private void checkRecruiterDetailsMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		RecruiterDetailsHome ban = new RecruiterDetailsHome(username);
		this.setVisible(false);
		ban.setVisible(true);
	}

	private void addEmployeeSkillMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddEmployeeSkill rh = new AddEmployeeSkill(username);
		this.setVisible(false);
		rh.setVisible(true);
	}

	private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		EmployeeSettings as = new EmployeeSettings(username);
		this.setVisible(false);
		as.setVisible(true);
	}

	private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		LoginMain lm = new LoginMain();
		this.setVisible(false);
		lm.setVisible(true);
	}

	private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {
		SkillType skt = new SkillType();
		String emplId = addEmployeeId.getText();
		int emplId1 = Integer.parseInt(emplId);
		String name = empl.getEmployeeNameById(emplId1);
		String emplSkillType = (String) jComboBox1.getSelectedItem();
		String emplSkillLevel = (String) jComboBox2.getSelectedItem();
		int emplSkillTypeName = skt.getSkillTypeIdByName(emplSkillType);
		EmployeeSkill emplSkill = new EmployeeSkill(emplId1, emplSkillTypeName,
				emplSkillLevel);
		int flag = emplSkill.addEmployeeSkill();
		if (flag != 0) {
			model.addRow(new Object[] { emplId1, name, emplSkillType,
					emplSkillLevel });
		}
	}

	@Override
	public void itemStateChanged(ItemEvent e) {
		if (e.getStateChange() == ItemEvent.SELECTED) {
			if (e.getSource() == jComboBox1) {
				if (jComboBox1.getSelectedItem().equals("NEW SKILL TYPE")) {
					AddSkillTypeHome sth = new AddSkillTypeHome(username);
					this.setVisible(false);
					sth.setVisible(true);
				}
			}
		}

	}
	private void processTableClick() {
		String employeeId = null;
		String skill_type = null;
		if (jTable.getValueAt(jTable.getSelectedRow(), 0) != null) {
			employeeId = jTable.getValueAt(jTable.getSelectedRow(), 0)
					.toString();
			skill_type = jTable.getValueAt(jTable.getSelectedRow(), 2)
					.toString();
		}
		SkillType st = new SkillType();
		int skill_type_id = st.getSkillTypeIdByName(skill_type);
		String opt[] = new String[] { "Delete", "Cancle" };
		int choice = JOptionPane.showOptionDialog(null,
				"Which operate do you want?", "Operation",
				JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
				opt, opt[1]);
		switch (opt[choice]) {
		case "Delete":
			processDelete(Integer.parseInt(employeeId), skill_type_id);
			break;
		case "Cancle":
			processCancle();
			break;
		}
	}

	private void processCancle() {

	}

	private void processDelete(int employeeId, int skillTypeId) {
		String str = "ARE YOU SURE TO DELETE EMPLOYEE ID " + employeeId
				+ " SKILL TYPE ID " + skillTypeId;
		int deleteChoice = JOptionPane.showConfirmDialog(null, str, "Delete",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		if (deleteChoice == JOptionPane.YES_OPTION) {
			if (employeeId != 0 && skillTypeId != 0) {
				EmployeeSkill es = new EmployeeSkill();
				if (es.getEmployeeSkills(employeeId, skillTypeId) == true) {
					es.deleteEmployeeSkill(employeeId);
				}
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger
					.getLogger(AddEmployeeSkill.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger
					.getLogger(AddEmployeeSkill.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger
					.getLogger(AddEmployeeSkill.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger
					.getLogger(AddEmployeeSkill.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddEmployeeSkill().setVisible(true);
			}
		});
	}

}
