/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import javax.swing.JOptionPane;

import view.myapp.LoginMain;
import model.SkillType;

/**
 *
 * @author Yuzana Zaw Zaw
 */
public class AddSkillTypeHome extends javax.swing.JFrame {

	/**
	 * Creates new form AddSkillTypeHome
	 */
	String username;

	public AddSkillTypeHome() {
		initComponents();
	}

	public AddSkillTypeHome(String username) {
		this.username = username;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		kGradientPanel1 = new keeptoo.KGradientPanel();
		jPanel3 = new javax.swing.JPanel();
		title1 = new javax.swing.JLabel();
		skillTypeLbl = new javax.swing.JLabel();
		saveSkillType = new javax.swing.JTextField();
		registerButton = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();
		subMainPanel = new javax.swing.JPanel();
		jSeparator3 = new javax.swing.JSeparator();
		titleLbl = new javax.swing.JLabel();
		updateEmployeeButton = new javax.swing.JPanel();
		updateEmployeeProfile = new javax.swing.JLabel();
		checkRecruiterDetails = new javax.swing.JPanel();
		checkRecruiterLbl = new javax.swing.JLabel();
		addEmployeeSkill = new javax.swing.JPanel();
		addEmployeeSkillLbl = new javax.swing.JLabel();
		settingsButton = new javax.swing.JPanel();
		settingsLbl = new javax.swing.JLabel();
		logOutButton = new javax.swing.JPanel();
		logoutLbl = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		xpanel = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		ypanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		kGradientPanel1.setkEndColor(new java.awt.Color(102, 0, 153));
		kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
		kGradientPanel1.setMaximumSize(new java.awt.Dimension(2147483647,
				2147483647));
		kGradientPanel1.setMinimumSize(new java.awt.Dimension(1060, 270));
		kGradientPanel1.setPreferredSize(new java.awt.Dimension(1060, 646));
		kGradientPanel1.setLayout(null);

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setForeground(new java.awt.Color(204, 204, 204));
		jPanel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title1.setText("Adding Skill Type");

		skillTypeLbl.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		skillTypeLbl.setForeground(new java.awt.Color(102, 102, 102));
		skillTypeLbl.setText("NEW SKILL NAME");

		saveSkillType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		saveSkillType.setForeground(new java.awt.Color(102, 102, 102));
		saveSkillType.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		registerButton.setBackground(new java.awt.Color(0, 0, 51));
		registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				registerButtonMouseClicked(evt);
			}
		});
		registerButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(204, 204, 204));
		jLabel10.setText("EMAIL");
		registerButton.add(jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1,
						-1));

		jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(204, 204, 204));
		jLabel14.setText("Save");
		registerButton.add(jLabel14,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1,
						-1));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap(44, Short.MAX_VALUE)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																skillTypeLbl)
														.addComponent(
																saveSkillType,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																278,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(62,
																				62,
																				62)
																		.addComponent(
																				registerButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				150,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(38, 38, 38))
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(35, 35, 35)
										.addComponent(
												title1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												278,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addComponent(title1)
										.addGap(37, 37, 37)
										.addComponent(skillTypeLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												saveSkillType,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(37, 37, 37)
										.addComponent(
												registerButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(43, Short.MAX_VALUE)));

		kGradientPanel1.add(jPanel3);
		jPanel3.setBounds(590, 30, 360, 240);

		jTable.setForeground(new java.awt.Color(204, 204, 255));
		jTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null },
						{ null, null }, { null, null } }, new String[] {
						"Skill Type Id", "Description " }));
		
		jScrollPane4.setViewportView(jTable);
		jScrollPane4.setVisible(false);
		kGradientPanel1.add(jScrollPane4);
		jScrollPane4.setBounds(550, 320, 452, 320);

		subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

		titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(204, 204, 204));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("RM SYS");
		titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		updateEmployeeButton.setBackground(new java.awt.Color(0, 0, 51));
		updateEmployeeButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						updateEmployeeButtonMouseClicked(evt);
					}
				});
		updateEmployeeButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		updateEmployeeProfile
				.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		updateEmployeeProfile.setForeground(new java.awt.Color(240, 240, 240));
		updateEmployeeProfile
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		updateEmployeeProfile.setText("Update Profile");
		updateEmployeeButton.add(updateEmployeeProfile,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		checkRecruiterDetails.setBackground(new java.awt.Color(0, 0, 51));
		checkRecruiterDetails
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						checkRecruiterDetailsMouseClicked(evt);
					}
				});
		checkRecruiterDetails
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		checkRecruiterLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		checkRecruiterLbl.setForeground(new java.awt.Color(240, 240, 240));
		checkRecruiterLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		checkRecruiterLbl.setText("Check Recruiter Detail");
		checkRecruiterDetails.add(checkRecruiterLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320,
						30));

		addEmployeeSkill.setBackground(new java.awt.Color(0, 0, 51));
		addEmployeeSkill.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addEmployeeSkillMouseClicked(evt);
			}
		});
		addEmployeeSkill
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		addEmployeeSkillLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		addEmployeeSkillLbl.setForeground(new java.awt.Color(240, 240, 240));
		addEmployeeSkillLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		addEmployeeSkillLbl.setText("Add Employee Skill");
		addEmployeeSkill.add(addEmployeeSkillLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 310,
						30));

		settingsButton.setBackground(new java.awt.Color(0, 0, 51));
		settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				settingsButtonMouseClicked(evt);
			}
		});
		settingsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		settingsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		settingsLbl.setForeground(new java.awt.Color(240, 240, 240));
		settingsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		settingsLbl.setText("Settings");
		settingsButton.add(settingsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		logOutButton.setBackground(new java.awt.Color(0, 0, 51));
		logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logOutButtonMouseClicked(evt);
			}
		});
		logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
		logoutLbl.setText("Log Out");
		logOutButton.add(logoutLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(
				subMainPanel);
		subMainPanel.setLayout(subMainPanelLayout);
		subMainPanelLayout
				.setHorizontalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								settingsButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								logOutButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								subMainPanelLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												checkRecruiterDetails,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												addEmployeeSkill,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												331,
																												Short.MAX_VALUE)
																										.addComponent(
																												updateEmployeeButton,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))))
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addGap(46,
																				46,
																				46)
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								titleLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								257,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jSeparator3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								268,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		subMainPanelLayout
				.setVerticalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(titleLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(129, 129, 129)
										.addComponent(
												updateEmployeeButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												checkRecruiterDetails,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addEmployeeSkill,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												settingsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												138, Short.MAX_VALUE)
										.addComponent(
												logOutButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(66, 66, 66)));

		kGradientPanel1.add(subMainPanel);
		subMainPanel.setBounds(0, 0, 343, 650);

		jPanel2.setOpaque(false);

		xpanel.setBackground(new java.awt.Color(0, 0, 51));
		xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xpanelMouseClicked(evt);
			}
		});

		jLabel9.setBackground(new java.awt.Color(0, 0, 51));
		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("X");

		javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(
				xpanel);
		xpanel.setLayout(xpanelLayout);
		xpanelLayout.setHorizontalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xpanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel9)
						.addContainerGap()));
		xpanelLayout.setVerticalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel9, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		ypanel.setBackground(new java.awt.Color(0, 0, 51));
		ypanel.setForeground(new java.awt.Color(0, 0, 51));
		ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ypanelMouseClicked(evt);
			}
		});

		jLabel12.setBackground(new java.awt.Color(0, 0, 0));
		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("-");

		javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(
				ypanel);
		ypanel.setLayout(ypanelLayout);
		ypanelLayout.setHorizontalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel12)
						.addContainerGap()));
		ypanelLayout.setVerticalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout.createSequentialGroup()
						.addGap(0, 1, Short.MAX_VALUE).addComponent(jLabel12)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout
						.createSequentialGroup()
						.addGap(0, 13, Short.MAX_VALUE)
						.addComponent(ypanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(xpanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		kGradientPanel1.add(jPanel2);
		jPanel2.setBounds(1120, 10, 80, 30);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 1244,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(12, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(9, Short.MAX_VALUE)));

		setSize(new java.awt.Dimension(1262, 661));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		String newSkillType = saveSkillType.getText();
		// System.out.println("NEW SKILL TYPE::::"+newSkillType);
		if (!newSkillType.equals("")) {
			SkillType st = new SkillType(newSkillType);
			st.saveSkillType();
			AddEmployeeSkill av = new AddEmployeeSkill(username);
			this.setVisible(false);
			av.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "Enter New Skill Type",
					"HEY!", JOptionPane.ERROR_MESSAGE);
			AddSkillTypeHome av = new AddSkillTypeHome(username);
			this.setVisible(false);
			av.setVisible(true);
		}

	}

	private void updateEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// System.out.println("USERNAME::"+username);
		UpdateEmployeeHome eh = new UpdateEmployeeHome(username);
		this.setVisible(false);
		eh.setVisible(true);
	}

	private void checkRecruiterDetailsMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		RecruiterDetailsHome ban=new RecruiterDetailsHome(username);
        this.setVisible(false);
        ban.setVisible(true);
	}

	private void addEmployeeSkillMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddEmployeeSkill rh = new AddEmployeeSkill(username);
		this.setVisible(false);
		rh.setVisible(true);
	}

	private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		EmployeeSettings as = new EmployeeSettings(username);
		this.setVisible(false);
		as.setVisible(true);
	}

	private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		LoginMain lm = new LoginMain();
		this.setVisible(false);
		lm.setVisible(true);
	}

	private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setState(AddSkillTypeHome.ICONIFIED);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger
					.getLogger(AddSkillTypeHome.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger
					.getLogger(AddSkillTypeHome.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger
					.getLogger(AddSkillTypeHome.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger
					.getLogger(AddSkillTypeHome.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddSkillTypeHome().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel addEmployeeSkill;
	private javax.swing.JLabel addEmployeeSkillLbl;
	private javax.swing.JPanel checkRecruiterDetails;
	private javax.swing.JLabel checkRecruiterLbl;
	private javax.swing.JLabel skillTypeLbl;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JTable jTable;
	private keeptoo.KGradientPanel kGradientPanel1;
	private javax.swing.JPanel logOutButton;
	private javax.swing.JLabel logoutLbl;
	private javax.swing.JPanel registerButton;
	private javax.swing.JPanel settingsButton;
	private javax.swing.JLabel settingsLbl;
	private javax.swing.JPanel subMainPanel;
	private javax.swing.JLabel title1;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JPanel updateEmployeeButton;
	private javax.swing.JLabel updateEmployeeProfile;
	private javax.swing.JTextField saveSkillType;
	private javax.swing.JPanel xpanel;
	private javax.swing.JPanel ypanel;
	// End of variables declaration
}
