package view.employee;

import java.awt.Color;

import view.myapp.LoginMain;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yuzana Zaw Zaw
 */
public class EmployeeHome extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeHome
     */
    private String ename,username;

    // Variables declaration - do not modify                     
    private javax.swing.JPanel addEmployeeButton;
    private javax.swing.JPanel checkRecruiterButton;
    private javax.swing.JLabel checkRecruiterLbl;
    private javax.swing.JLabel adminRoomLabel;
    private javax.swing.JPanel adminRoomPanel;
    private javax.swing.JLabel addEmployeeSkillLbl;
    private javax.swing.JPanel addEmployeeSkillButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JPanel settingsButton;
    private javax.swing.JLabel settingsLbl;
    private javax.swing.JPanel subMainPanel;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JTextField welcomeText;
    private javax.swing.JPanel xpanel;
    private javax.swing.JPanel xyPanel;
    private javax.swing.JPanel ypanel;
    // End of variables declaration 
    public EmployeeHome()
    {
    	initComponents();
    }
    public EmployeeHome(String id,String ename) {
        username=id;
        this.ename=ename;
        initComponents();
        welcomeText(ename);
    }
    
    public void welcomeText(String namee)
    {
    	welcomeText.setText(namee);
    	welcomeText.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        adminRoomPanel = new javax.swing.JPanel();
        adminRoomLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        welcomeLabel = new javax.swing.JLabel();
        welcomeText = new javax.swing.JTextField();
        xyPanel = new javax.swing.JPanel();
        xpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ypanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        subMainPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        titleLbl = new javax.swing.JLabel();
        addEmployeeButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        checkRecruiterButton = new javax.swing.JPanel();
        checkRecruiterLbl = new javax.swing.JLabel();
        addEmployeeSkillButton = new javax.swing.JPanel();
        addEmployeeSkillLbl = new javax.swing.JLabel();
        settingsButton = new javax.swing.JPanel();
        settingsLbl = new javax.swing.JLabel();
        logOutButton = new javax.swing.JPanel();
        logoutLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminRoomPanel.setBackground(new java.awt.Color(204, 204, 255));

        adminRoomLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminRoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminRoomLabel.setText("Employee Room");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");

        welcomeText.setBackground(new java.awt.Color(204, 204, 204));
        welcomeText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeText.setBorder(null);

        javax.swing.GroupLayout adminRoomPanelLayout = new javax.swing.GroupLayout(adminRoomPanel);
        adminRoomPanel.setLayout(adminRoomPanelLayout);
        adminRoomPanelLayout.setHorizontalGroup(
            adminRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminRoomPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(adminRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminRoomPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(77, 77, 77)
                        .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(adminRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adminRoomPanelLayout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        adminRoomPanelLayout.setVerticalGroup(
            adminRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminRoomPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(adminRoomLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(adminRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(adminRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminRoomPanelLayout.createSequentialGroup()
                    .addContainerGap(171, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        jPanel2.add(adminRoomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 710, 200));

        xyPanel.setOpaque(false);

        xpanel.setBackground(new java.awt.Color(255, 255, 255));
        xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xpanelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("X");

        javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(xpanel);
        xpanel.setLayout(xpanelLayout);
        xpanelLayout.setHorizontalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        xpanelLayout.setVerticalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ypanel.setBackground(new java.awt.Color(255, 255, 255));
        ypanel.setForeground(new java.awt.Color(255, 255, 255));
        ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ypanelMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("-");

        javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(ypanel);
        ypanel.setLayout(ypanelLayout);
        ypanelLayout.setHorizontalGroup(
            ypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ypanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        ypanelLayout.setVerticalGroup(
            ypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ypanelLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        javax.swing.GroupLayout xyPanelLayout = new javax.swing.GroupLayout(xyPanel);
        xyPanel.setLayout(xyPanelLayout);
        xyPanelLayout.setHorizontalGroup(
            xyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xyPanelLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(ypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(xpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        xyPanelLayout.setVerticalGroup(
            xyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(xyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

        titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(204, 204, 204));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("RM SYS");
        titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addEmployeeButton.setBackground(new java.awt.Color(0, 0, 51));
        addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseClicked(evt);
            }
        });
        addEmployeeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update Profile");
        addEmployeeButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        checkRecruiterButton.setBackground(new java.awt.Color(0, 0, 51));
        checkRecruiterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkRecruiterButtonMouseClicked(evt);
            }
        });
        checkRecruiterButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkRecruiterLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        checkRecruiterLbl.setForeground(new java.awt.Color(240, 240, 240));
        checkRecruiterLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkRecruiterLbl.setText("Check Recruiter Detail");
        checkRecruiterButton.add(checkRecruiterLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 30));

        addEmployeeSkillButton.setBackground(new java.awt.Color(0, 0, 51));
        addEmployeeSkillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeSkillButtonMouseClicked(evt);
            }
        });
        addEmployeeSkillButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addEmployeeSkillLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addEmployeeSkillLbl.setForeground(new java.awt.Color(240, 240, 240));
        addEmployeeSkillLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addEmployeeSkillLbl.setText("Add Employee Skill");
        addEmployeeSkillButton.add(addEmployeeSkillLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 310, 30));

        settingsButton.setBackground(new java.awt.Color(0, 0, 51));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
        });
        settingsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        settingsLbl.setForeground(new java.awt.Color(240, 240, 240));
        settingsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsLbl.setText("Settings");
        settingsButton.add(settingsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 30));

        logOutButton.setBackground(new java.awt.Color(0, 0, 51));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });
        logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
        logoutLbl.setText("Log Out");
        logOutButton.add(logoutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(subMainPanel);
        subMainPanel.setLayout(subMainPanelLayout);
        subMainPanelLayout.setHorizontalGroup(
            subMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMainPanelLayout.createSequentialGroup()
                .addGroup(subMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subMainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(subMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(subMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkRecruiterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addEmployeeSkillButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                .addComponent(addEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(subMainPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(subMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subMainPanelLayout.setVerticalGroup(
            subMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkRecruiterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmployeeSkillButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanel2.add(subMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        setSize(new java.awt.Dimension(1095, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        System.exit(0);
    }                                   
                                

    private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        setState(EmployeeHome.ICONIFIED);
    }                                   

    private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
        UpdateEmployeeHome av=new UpdateEmployeeHome(username);
        this.setVisible(false);
        av.setVisible(true);
    }                                              

    private void checkRecruiterButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
        RecruiterDetailsHome ban=new RecruiterDetailsHome(username);
        this.setVisible(false);
        ban.setVisible(true);
        
    }                                               

    private void addEmployeeSkillButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        // TODO add your handling code here:
        AddEmployeeSkill rh=new AddEmployeeSkill(username);
        this.setVisible(false);
        rh.setVisible(true);
    }                                                  
                                               

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        EmployeeSettings as=new EmployeeSettings(username);
        this.setVisible(false);
        as.setVisible(true);
    }                                           
                                      

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        LoginMain lm=new LoginMain();
        this.setVisible(false);
        lm.setVisible(true);
    }                                         
                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeHome().setVisible(true);
            }
        });
    }                  
}
