/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.ProcessBuilder.Redirect;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import dao.DatabaseUtils;
import view.myapp.LoginMain;

/**
 *
 * @author user
 */
public class RecruiterDetailsHome extends javax.swing.JFrame {

	/**
	 * Creates new form RecruiterDetailsHome
	 */
	String username;
	String[] columnNames = { "Name", "Company Name", "Phone No", "Email",
			"Address" };
	DefaultTableModel model = new DefaultTableModel();
	// Variables declaration - do not modify
		private javax.swing.JPanel addEmployeeSkill;
		private javax.swing.JLabel addEmployeeSkillLbl;
		private javax.swing.JLabel addLbl;
		private javax.swing.JPanel checkRecruiterDetails;
		private javax.swing.JLabel checkRecruiterLbl;
		private javax.swing.JLabel jLabel10;
		private javax.swing.JLabel jLabel11;
		private javax.swing.JLabel jLabel12;
		private javax.swing.JLabel jLabel19;
		private javax.swing.JLabel jLabel30;
		private javax.swing.JPanel jPanel1;
		private javax.swing.JPanel jPanel2;
		private javax.swing.JScrollPane jScrollPane4;
		private javax.swing.JSeparator jSeparator3;
		private javax.swing.JTable jTable;
		private keeptoo.KGradientPanel kGradientPanel1;
		private javax.swing.JPanel logOutButton;
		private javax.swing.JLabel logoutLbl;
		private javax.swing.JPanel searchButton;
		private javax.swing.JTextField searchCompanyName;
		private javax.swing.JTextField searchName;
		private javax.swing.JPanel settingsButton;
		private javax.swing.JLabel settingsLbl;
		private javax.swing.JPanel subMainPanel;
		private javax.swing.JLabel title;
		private javax.swing.JLabel titleLbl;
		private javax.swing.JPanel updateEmployeeButton;
		private javax.swing.JLabel updateEmployeeProfile;
		private javax.swing.JPanel xpanel;
		private javax.swing.JPanel ypanel;
		// End of variables declaration

	public RecruiterDetailsHome() {
		initComponents();
	}

	public RecruiterDetailsHome(String username) {
		this.username = username;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		kGradientPanel1 = new keeptoo.KGradientPanel();
		jPanel2 = new javax.swing.JPanel();
		xpanel = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		ypanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		subMainPanel = new javax.swing.JPanel();
		jSeparator3 = new javax.swing.JSeparator();
		titleLbl = new javax.swing.JLabel();
		updateEmployeeButton = new javax.swing.JPanel();
		updateEmployeeProfile = new javax.swing.JLabel();
		checkRecruiterDetails = new javax.swing.JPanel();
		checkRecruiterLbl = new javax.swing.JLabel();
		addEmployeeSkill = new javax.swing.JPanel();
		addEmployeeSkillLbl = new javax.swing.JLabel();
		settingsButton = new javax.swing.JPanel();
		settingsLbl = new javax.swing.JLabel();
		logOutButton = new javax.swing.JPanel();
		logoutLbl = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		searchButton = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		addLbl = new javax.swing.JLabel();
		title = new javax.swing.JLabel();
		searchCompanyName = new javax.swing.JTextField();
		searchName = new javax.swing.JTextField();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		kGradientPanel1.setkEndColor(new java.awt.Color(102, 0, 153));
		kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
		kGradientPanel1.setMaximumSize(new java.awt.Dimension(2147483647,
				2147483647));
		kGradientPanel1.setMinimumSize(new java.awt.Dimension(1060, 270));
		kGradientPanel1.setPreferredSize(new java.awt.Dimension(1060, 646));
		kGradientPanel1.setLayout(null);

		jPanel2.setOpaque(false);

		xpanel.setBackground(new java.awt.Color(0, 0, 51));
		xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xpanelMouseClicked(evt);
			}
		});

		jLabel11.setBackground(new java.awt.Color(0, 0, 51));
		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("X");

		javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(
				xpanel);
		xpanel.setLayout(xpanelLayout);
		xpanelLayout.setHorizontalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xpanelLayout
						.createSequentialGroup()
						.addGap(0, 6, Short.MAX_VALUE)
						.addComponent(jLabel11,
								javax.swing.GroupLayout.PREFERRED_SIZE, 13,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		xpanelLayout.setVerticalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel11, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		ypanel.setBackground(new java.awt.Color(0, 0, 51));
		ypanel.setForeground(new java.awt.Color(0, 0, 51));
		ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ypanelMouseClicked(evt);
			}
		});

		jLabel12.setBackground(new java.awt.Color(0, 0, 0));
		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("-");

		javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(
				ypanel);
		ypanel.setLayout(ypanelLayout);
		ypanelLayout.setHorizontalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel12)
						.addContainerGap()));
		ypanelLayout.setVerticalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout.createSequentialGroup()
						.addGap(0, 1, Short.MAX_VALUE).addComponent(jLabel12)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout
						.createSequentialGroup()
						.addGap(0, 13, Short.MAX_VALUE)
						.addComponent(ypanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(xpanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		kGradientPanel1.add(jPanel2);
		jPanel2.setBounds(830, 10, 80, 30);

		subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

		titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(204, 204, 204));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("RM SYS");
		titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		updateEmployeeButton.setBackground(new java.awt.Color(0, 0, 51));
		updateEmployeeButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						updateEmployeeButtonMouseClicked(evt);
					}
				});
		updateEmployeeButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		updateEmployeeProfile
				.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		updateEmployeeProfile.setForeground(new java.awt.Color(240, 240, 240));
		updateEmployeeProfile
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		updateEmployeeProfile.setText("Update Profile");
		updateEmployeeButton.add(updateEmployeeProfile,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		checkRecruiterDetails.setBackground(new java.awt.Color(0, 0, 51));
		checkRecruiterDetails
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						checkRecruiterDetailsMouseClicked(evt);
					}
				});
		checkRecruiterDetails
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		checkRecruiterLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		checkRecruiterLbl.setForeground(new java.awt.Color(240, 240, 240));
		checkRecruiterLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		checkRecruiterLbl.setText("Check Recruiter Detail");
		checkRecruiterDetails.add(checkRecruiterLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320,
						30));

		addEmployeeSkill.setBackground(new java.awt.Color(0, 0, 51));
		addEmployeeSkill.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addEmployeeSkillMouseClicked(evt);
			}
		});
		addEmployeeSkill
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		addEmployeeSkillLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		addEmployeeSkillLbl.setForeground(new java.awt.Color(240, 240, 240));
		addEmployeeSkillLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		addEmployeeSkillLbl.setText("Add Employee Skill");
		addEmployeeSkill.add(addEmployeeSkillLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 310,
						30));

		settingsButton.setBackground(new java.awt.Color(0, 0, 51));
		settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				settingsButtonMouseClicked(evt);
			}
		});
		settingsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		settingsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		settingsLbl.setForeground(new java.awt.Color(240, 240, 240));
		settingsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		settingsLbl.setText("Settings");
		settingsButton.add(settingsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		logOutButton.setBackground(new java.awt.Color(0, 0, 51));
		logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logOutButtonMouseClicked(evt);
			}
		});
		logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
		logoutLbl.setText("Log Out");
		logOutButton.add(logoutLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(
				subMainPanel);
		subMainPanel.setLayout(subMainPanelLayout);
		subMainPanelLayout
				.setHorizontalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								settingsButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								logOutButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								subMainPanelLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												checkRecruiterDetails,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												addEmployeeSkill,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												331,
																												Short.MAX_VALUE)
																										.addComponent(
																												updateEmployeeButton,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))))
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addGap(46,
																				46,
																				46)
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								titleLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								257,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jSeparator3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								268,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		subMainPanelLayout
				.setVerticalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(titleLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(129, 129, 129)
										.addComponent(
												updateEmployeeButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												checkRecruiterDetails,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addEmployeeSkill,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												settingsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												138, Short.MAX_VALUE)
										.addComponent(
												logOutButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(66, 66, 66)));

		kGradientPanel1.add(subMainPanel);
		subMainPanel.setBounds(0, 0, 343, 650);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setForeground(new java.awt.Color(204, 204, 204));
		jPanel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(102, 102, 102));
		jLabel19.setText("Name");

		jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel30.setForeground(new java.awt.Color(102, 102, 102));
		jLabel30.setText("Company Name");

		searchButton.setBackground(new java.awt.Color(0, 0, 51));
		searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				searchButtonMouseClicked(evt);
			}

		});
		searchButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(204, 204, 204));
		jLabel10.setText("EMAIL");
		searchButton.add(jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1,
						-1));

		addLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		addLbl.setForeground(new java.awt.Color(204, 204, 204));
		addLbl.setText("Search");

		searchButton.add(addLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1,
						-1));

		title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title.setText("Recruiter Details");

		searchCompanyName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		searchCompanyName.setForeground(new java.awt.Color(102, 102, 102));
		searchCompanyName
				.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2,
						0, new java.awt.Color(12, 91, 160)));

		searchName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		searchName.setForeground(new java.awt.Color(102, 102, 102));
		searchName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0,
				2, 0, new java.awt.Color(12, 91, 160)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(65,
																				65,
																				65)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel30)
																										.addGap(34,
																												34,
																												34)
																										.addComponent(
																												searchCompanyName,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												181,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jLabel19)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(26,
																												26,
																												26)
																										.addComponent(
																												title,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												245,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(120,
																				120,
																				120)
																		.addComponent(
																				searchButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				150,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(48, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.addContainerGap(173,
																Short.MAX_VALUE)
														.addComponent(
																searchName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																181,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(46, 46, 46))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addComponent(title)
										.addGap(34, 34, 34)
										.addComponent(jLabel19)
										.addGap(20, 20, 20)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel30)
														.addComponent(
																searchCompanyName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(29, 29, 29)
										.addComponent(
												searchButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(36, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGap(62, 62, 62)
														.addComponent(
																searchName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addContainerGap(146,
																Short.MAX_VALUE))));

		kGradientPanel1.add(jPanel1);
		jPanel1.setBounds(430, 50, 400, 230);

		jTable.setForeground(new java.awt.Color(51,0,51));
		model.setColumnIdentifiers(columnNames);
		jTable.setModel(model);
		jTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
		jTable.setFillsViewportHeight(true);

		jScrollPane4.setViewportView(jTable);

		kGradientPanel1.add(jScrollPane4);
		jScrollPane4.setBounds(410, 360, 452, 250);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 956,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(288, 288, 288)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 640,
								Short.MAX_VALUE).addContainerGap()));

		setSize(new java.awt.Dimension(961, 646));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setState(RecruiterDetailsHome.ICONIFIED);
	}

	private void updateEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		UpdateEmployeeHome av = new UpdateEmployeeHome(username);
		this.setVisible(false);
		av.setVisible(true);
	}

	private void checkRecruiterDetailsMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		RecruiterDetailsHome rd = new RecruiterDetailsHome(username);
		this.setVisible(false);
		rd.setVisible(true);
	}

	private void addEmployeeSkillMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddEmployeeSkill rh = new AddEmployeeSkill(username);
		this.setVisible(false);
		rh.setVisible(true);
	}

	private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		EmployeeSettings as = new EmployeeSettings(username);
		this.setVisible(false);
		as.setVisible(true);
	}

	private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		LoginMain lm = new LoginMain();
		this.setVisible(false);
		lm.setVisible(true);
	}

	private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {
		model.setRowCount(0);
		String searchNameData = searchName.getText();
		String searchCName = searchCompanyName.getText();

		String name;
		String firstName;
		String lastName;
		String companyName;
		String phoneNo;
		String email;
		String address;

		String mainSql = "Select * " + "from Recruiters ";

		if (!searchNameData.equals("") && !searchCName.equals("")) {
			mainSql += "where first_name LIKE UPPER('%" + searchNameData
					+ "%') " + "or last_name LIKE UPPER('%" + searchNameData
					+ "%') ";
			mainSql += "and company_name LIKE UPPER('%" + searchCName + "%') ";
		} else if (!searchNameData.equals("")) {
			mainSql += "where first_name LIKE UPPER('%" + searchNameData
					+ "%') " + "or last_name LIKE UPPER('%" + searchNameData
					+ "%') ";
		} else if (!searchCName.equals("")) {
			mainSql += "where company_name LIKE UPPER('%" + searchCName
					+ "%') ";
		}if (searchNameData.equals("") && searchCName.equals("")) {
			mainSql="Select * " + "from Recruiters ";
		}

		//System.out.println("SQL:::" + mainSql);
		DatabaseUtils conn = new DatabaseUtils();
		conn.OpenConnection();
		ResultSet rs1 = conn.GetData(mainSql);
		int i = 0;
		try {
			while (rs1.next()) {
				firstName = rs1.getString("first_name");
				lastName = rs1.getString("last_name");
				name = firstName + " " + lastName;
				companyName = rs1.getString("company_name");
				phoneNo = rs1.getString("phone_no");
				email = rs1.getString("email");
				address = rs1.getString("address");
				model.addRow(new Object[] { name, companyName, phoneNo, email,
						address });
				searchName.setText("");
				searchCompanyName.setText("");
				i++;
			}
			searchName.setText("");
			searchCompanyName.setText("");
			conn.CloseConnection();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if (i < 1) {
			JOptionPane.showMessageDialog(null, "No Record Found", "Error",
					JOptionPane.ERROR_MESSAGE);
		}
		if (i == 1) {
			System.out.println(i + " Record Found");
		} else {
			System.out.println(i + " Records Found");
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					RecruiterDetailsHome.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					RecruiterDetailsHome.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					RecruiterDetailsHome.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					RecruiterDetailsHome.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RecruiterDetailsHome().setVisible(true);
			}
		});
	}

	
}
