package view.admin;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import utilits.EmailValidation;
import view.employee.EmployeeDetailsForEmployeeHome;
import view.myapp.LoginMain;
import model.Employee;
import model.EmployeeImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yuzana Zaw Zaw
 */
public class AddEmployeeHome extends javax.swing.JFrame {

	/**
	 * Creates new form AddEmployeeHome
	 */
	private String username;
	File selectedFile = null;
	String image_Path = null;
	String path = null;
	private javax.swing.ButtonGroup btnGroup;
	// Variables declaration - do not modify
	private javax.swing.JPanel addEmployeeButton;
	private javax.swing.JPanel addRecruiterButton;
	private javax.swing.JLabel addRecruiterLbl;
	private javax.swing.JButton browse;
	private javax.swing.JRadioButton checkFemale;
	private javax.swing.JRadioButton checkMale;
	private com.toedter.calendar.JDateChooser dobCombo;
	private javax.swing.JLabel emplDetailsLbl;
	private javax.swing.JPanel employeeDetailsButton;
	private javax.swing.JLabel employeeIdlbl;
	private javax.swing.JLabel fatherNameLbl;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JPanel logOutButton;
	private javax.swing.JLabel logoutLbl;
	private javax.swing.JLabel profileImage;
	private javax.swing.JPanel registerButton;
	private javax.swing.JTextField registerIdTxt;
	private javax.swing.JPanel settingsButton;
	private javax.swing.JLabel settingsLbl;
	private javax.swing.JPanel subMainPanel;
	private javax.swing.JLabel title;
	private javax.swing.JLabel title1;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JTextField registerAddress;
	private javax.swing.JTextField registerEmail;
	private javax.swing.JTextField registerFatherName;
	private javax.swing.JTextField registerFirstName1;
	private javax.swing.JTextField registerLastName;
	private javax.swing.JTextField registerNRC;
	private javax.swing.JPasswordField registerPassword;
	private javax.swing.JTextField registerPhno;
	private javax.swing.JTextField registerQualification;
	private javax.swing.JTextField registerSecurity;
	private javax.swing.JTextField registerUniversity;
	private javax.swing.JTextField registerUsername;
	private javax.swing.JLabel uu;
	private javax.swing.JPanel xpanel;
	private javax.swing.JPanel xyPanel;
	private javax.swing.JPanel ypanel;

	// End of variables declaration

	public AddEmployeeHome() {
		initComponents();
	}

	public AddEmployeeHome(String username) {
		this.username = username;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		btnGroup = new javax.swing.ButtonGroup();
		jPanel2 = new javax.swing.JPanel();
		xyPanel = new javax.swing.JPanel();
		xpanel = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		ypanel = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		subMainPanel = new javax.swing.JPanel();
		jSeparator3 = new javax.swing.JSeparator();
		titleLbl = new javax.swing.JLabel();
		addEmployeeButton = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		addRecruiterButton = new javax.swing.JPanel();
		addRecruiterLbl = new javax.swing.JLabel();
		employeeDetailsButton = new javax.swing.JPanel();
		emplDetailsLbl = new javax.swing.JLabel();
		settingsButton = new javax.swing.JPanel();
		settingsLbl = new javax.swing.JLabel();
		logOutButton = new javax.swing.JPanel();
		logoutLbl = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		registerPassword = new javax.swing.JPasswordField();
		jLabel19 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		registerUniversity = new javax.swing.JTextField();
		jLabel33 = new javax.swing.JLabel();
		registerPhno = new javax.swing.JTextField();
		jLabel34 = new javax.swing.JLabel();
		registerAddress = new javax.swing.JTextField();
		uu = new javax.swing.JLabel();
		registerUsername = new javax.swing.JTextField();
		registerButton = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		registerEmail = new javax.swing.JTextField();
		checkMale = new javax.swing.JRadioButton();
		checkFemale = new javax.swing.JRadioButton();
		title = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		registerSecurity = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		registerQualification = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		registerFirstName1 = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		registerLastName = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		registerNRC = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		dobCombo = new com.toedter.calendar.JDateChooser();
		employeeIdlbl = new javax.swing.JLabel();
		registerIdTxt = new javax.swing.JTextField();
		title1 = new javax.swing.JLabel();
		fatherNameLbl = new javax.swing.JLabel();
		registerFatherName = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		browse = new javax.swing.JButton();
		profileImage = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jPanel2.setBackground(new java.awt.Color(204, 102, 255));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		xyPanel.setOpaque(false);

		xpanel.setBackground(new java.awt.Color(255, 255, 255));
		xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xpanelMouseClicked(evt);
			}

		});

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel7.setText("X");

		javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(
				xpanel);
		xpanel.setLayout(xpanelLayout);
		xpanelLayout.setHorizontalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xpanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel7)
						.addContainerGap()));
		xpanelLayout.setVerticalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel7, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		ypanel.setBackground(new java.awt.Color(255, 255, 255));
		ypanel.setForeground(new java.awt.Color(255, 255, 255));
		ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ypanelMouseClicked(evt);
			}

		});

		jLabel8.setBackground(new java.awt.Color(255, 255, 255));
		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel8.setText("-");

		javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(
				ypanel);
		ypanel.setLayout(ypanelLayout);
		ypanelLayout.setHorizontalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel8)
						.addContainerGap()));
		ypanelLayout.setVerticalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout.createSequentialGroup()
						.addGap(0, 1, Short.MAX_VALUE).addComponent(jLabel8)));

		javax.swing.GroupLayout xyPanelLayout = new javax.swing.GroupLayout(
				xyPanel);
		xyPanel.setLayout(xyPanelLayout);
		xyPanelLayout.setHorizontalGroup(xyPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xyPanelLayout
						.createSequentialGroup()
						.addGap(0, 37, Short.MAX_VALUE)
						.addComponent(ypanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(xpanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		xyPanelLayout.setVerticalGroup(xyPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		jPanel2.add(xyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				1180, 10, -1, -1));

		subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

		titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(204, 204, 204));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("RM SYS");
		titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		addEmployeeButton.setBackground(new java.awt.Color(0, 0, 51));
		addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addEmployeeButtonMouseClicked(evt);
			}

		});
		addEmployeeButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(240, 240, 240));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("Add Employee");
		addEmployeeButton.add(jLabel4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310,
						30));

		addRecruiterButton.setBackground(new java.awt.Color(0, 0, 51));
		addRecruiterButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addRecruiterButtonMouseClicked(evt);
			}

		});
		addRecruiterButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		addRecruiterLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		addRecruiterLbl.setForeground(new java.awt.Color(240, 240, 240));
		addRecruiterLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		addRecruiterLbl.setText("Add Recruiter");
		addRecruiterButton.add(addRecruiterLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310,
						30));

		employeeDetailsButton.setBackground(new java.awt.Color(0, 0, 51));
		employeeDetailsButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						employeeDetailsButtonMouseClicked(evt);
					}

				});
		employeeDetailsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		emplDetailsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		emplDetailsLbl.setForeground(new java.awt.Color(240, 240, 240));
		emplDetailsLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		emplDetailsLbl.setText("Employee Details");
		employeeDetailsButton.add(emplDetailsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, 310,
						30));

		settingsButton.setBackground(new java.awt.Color(0, 0, 51));
		settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				settingsButtonMouseClicked(evt);
			}

		});
		settingsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		settingsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		settingsLbl.setForeground(new java.awt.Color(240, 240, 240));
		settingsLbl.setText("Settings");
		settingsButton.add(settingsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		logOutButton.setBackground(new java.awt.Color(0, 0, 51));
		logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logOutButtonMouseClicked(evt);
			}

		});
		logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
		logoutLbl.setText("Log Out");
		logOutButton.add(logoutLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(
				subMainPanel);
		subMainPanel.setLayout(subMainPanelLayout);
		subMainPanelLayout
				.setHorizontalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																titleLbl,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																257,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jSeparator3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																268,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				addEmployeeButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				337,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addComponent(
																addRecruiterButton,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																employeeDetailsButton,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																subMainPanelLayout
																		.createSequentialGroup()
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								logOutButton,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								settingsButton,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								337,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap()));
		subMainPanelLayout
				.setVerticalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(titleLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(129, 129, 129)
										.addComponent(
												addEmployeeButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addRecruiterButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												employeeDetailsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												settingsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												152, Short.MAX_VALUE)
										.addComponent(
												logOutButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(32, 32, 32)));

		jPanel2.add(subMainPanel,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340,
						630));

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setForeground(new java.awt.Color(204, 204, 204));
		jPanel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(102, 102, 102));
		jLabel9.setText("Password");

		registerPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerPassword.setForeground(new java.awt.Color(102, 102, 102));
		registerPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(102, 102, 102));
		jLabel19.setText("Gender");

		jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel30.setForeground(new java.awt.Color(102, 102, 102));
		jLabel30.setText("What is your dream city?");

		registerUniversity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerUniversity.setForeground(new java.awt.Color(102, 102, 102));
		registerUniversity
				.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2,
						0, new java.awt.Color(12, 91, 160)));

		jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel33.setForeground(new java.awt.Color(102, 102, 102));
		jLabel33.setText("Phone No");

		registerPhno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerPhno.setForeground(new java.awt.Color(102, 102, 102));
		registerPhno.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel34.setForeground(new java.awt.Color(102, 102, 102));
		jLabel34.setText("Email");

		registerAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerAddress.setForeground(new java.awt.Color(102, 102, 102));
		registerAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		uu.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		uu.setForeground(new java.awt.Color(102, 102, 102));
		uu.setText("Username");

		registerUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerUsername.setForeground(new java.awt.Color(102, 102, 102));
		registerUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		registerButton.setBackground(new java.awt.Color(0, 0, 51));
		registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				registerButtonMouseClicked(evt);
			}

		});
		registerButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(204, 204, 204));
		jLabel10.setText("EMAIL");
		registerButton.add(jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1,
						-1));

		jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(204, 204, 204));
		jLabel14.setText("register");

		registerButton.add(jLabel14,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1,
						-1));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(102, 102, 102));
		jLabel1.setText("Address");

		registerEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerEmail.setForeground(new java.awt.Color(102, 102, 102));
		registerEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		checkMale.setText("Male");
		checkFemale.setText("Female");
		btnGroup.add(checkMale);
		btnGroup.add(checkFemale);

		title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title.setText("Add Employee Profile");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(102, 102, 102));
		jLabel5.setText("Qualification");

		registerSecurity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerSecurity.setForeground(new java.awt.Color(102, 102, 102));
		registerSecurity.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(102, 102, 102));
		jLabel6.setText("University Name");

		registerQualification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerQualification.setForeground(new java.awt.Color(102, 102, 102));
		registerQualification
				.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2,
						0, new java.awt.Color(12, 91, 160)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				title,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				245,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								registerQualification,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								278,
																								Short.MAX_VALUE)
																						.addComponent(
																								registerSecurity)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel5)
																														.addGroup(
																																jPanel1Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																		.addComponent(
																																				registerPhno,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				278,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				registerUniversity,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				278,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				jLabel33)
																																		.addComponent(
																																				jLabel30)
																																		.addComponent(
																																				jLabel19)
																																		.addGroup(
																																				jPanel1Layout
																																						.createSequentialGroup()
																																						.addComponent(
																																								checkMale,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								59,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addComponent(
																																								checkFemale)))
																														.addComponent(
																																jLabel6))
																										.addGap(0,
																												0,
																												Short.MAX_VALUE)))
																		.addGap(37,
																				37,
																				37))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												registerUsername,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												278,
																												Short.MAX_VALUE)
																										.addComponent(
																												registerPassword)
																										.addComponent(
																												uu)
																										.addComponent(
																												jLabel9))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												registerEmail)
																										.addComponent(
																												registerAddress,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												278,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel34)
																										.addComponent(
																												jLabel1)))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												registerButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(115, 115, 115)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(title)
										.addGap(52, 52, 52)
										.addComponent(jLabel19)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(checkMale)
														.addComponent(
																checkFemale))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel30)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerSecurity,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerQualification,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel6)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												registerUniversity,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel33)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												registerPhno,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel34)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerEmail,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												registerAddress,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(uu)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerUsername,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel9)
										.addGap(18, 18, 18)
										.addComponent(
												registerPassword,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				790, 0, 380, -1));

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setForeground(new java.awt.Color(204, 204, 204));
		jPanel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(102, 102, 102));
		jLabel11.setText("First Name");

		registerFirstName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerFirstName1.setForeground(new java.awt.Color(102, 102, 102));
		registerFirstName1
				.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2,
						0, new java.awt.Color(12, 91, 160)));

		jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(102, 102, 102));
		jLabel21.setText("Last Name");

		registerLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerLastName.setForeground(new java.awt.Color(102, 102, 102));
		registerLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel22.setForeground(new java.awt.Color(102, 102, 102));
		jLabel22.setText("NRC No");

		registerNRC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerNRC.setForeground(new java.awt.Color(102, 102, 102));
		registerNRC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0,
				2, 0, new java.awt.Color(12, 91, 160)));

		jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel24.setForeground(new java.awt.Color(102, 102, 102));
		jLabel24.setText("DOB");

		employeeIdlbl.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		employeeIdlbl.setForeground(new java.awt.Color(102, 102, 102));
		employeeIdlbl.setText("Employee Id");
		employeeIdlbl.setVisible(false);

		registerIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerIdTxt.setForeground(new java.awt.Color(102, 102, 102));
		registerIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));
		registerIdTxt.setVisible(false);

		title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title1.setText("Add Employee Profile");

		fatherNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		fatherNameLbl.setForeground(new java.awt.Color(102, 102, 102));
		fatherNameLbl.setText("Father Name");

		registerFatherName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		registerFatherName.setForeground(new java.awt.Color(102, 102, 102));
		registerFatherName
				.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2,
						0, new java.awt.Color(12, 91, 160)));

		jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel25.setText("Profile Image");

		browse.setText("BROWSE");
		browse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				browseActionPerformed(evt);
			}
		});

		profileImage.setBackground(new java.awt.Color(204, 204, 204));
		profileImage.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
		profileImage.setForeground(new java.awt.Color(204, 204, 204));
		profileImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		profileImage.setText("PROFILE IMAGE");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				title1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				278,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jLabel21,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								registerLastName,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								278,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel11,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel24,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								dobCombo,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								125,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								employeeIdlbl,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								registerIdTxt,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								registerFirstName1,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								fatherNameLbl,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								registerFatherName,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel22,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								registerNRC,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								278,
																								Short.MAX_VALUE)
																						.addComponent(
																								profileImage,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								145,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel25)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												browse)))
																		.addContainerGap(
																				47,
																				Short.MAX_VALUE)))));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addComponent(title1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												profileImage,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												126,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(browse)
														.addComponent(jLabel25))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(employeeIdlbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												registerIdTxt,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												registerFirstName1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel21)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerLastName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(fatherNameLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												registerFatherName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel22)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												registerNRC,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel24)
										.addGap(18, 18, 18)
										.addComponent(
												dobCombo,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(48, Short.MAX_VALUE)));

		jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				390, 0, -1, 630));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 1303,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(9, Short.MAX_VALUE)
						.addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 640,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		setSize(new java.awt.Dimension(1315, 655));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setState(AddEmployeeHome.ICONIFIED);
	}

	private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddEmployeeHome av = new AddEmployeeHome(username);
		this.setVisible(false);
		av.setVisible(true);
	}

	private void addRecruiterButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddRecruiterHome ban = new AddRecruiterHome();
		this.setVisible(false);
		ban.setVisible(true);
	}

	private void employeeDetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		EmployeeDetailsForEmployeeHome rh = new EmployeeDetailsForEmployeeHome(
				username);
		this.setVisible(false);
		rh.setVisible(true);
	}

	private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AdminSettings as = new AdminSettings(username);
		this.setVisible(false);
		as.setVisible(true);
	}

	private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		LoginMain lm = new LoginMain();
		this.setVisible(false);
		lm.setVisible(true);
	}

	private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {
		String first_name = registerFirstName1.getText();
		String last_name = registerLastName.getText();
		String user_name = registerUsername.getText();
		String father_name = registerFatherName.getText();
		String pass_word = registerPassword.getText();
		String phone_no = registerPhno.getText();
		String gen_der = checkMale.isSelected() ? "Male" : "Female";
		String e_mail = null;
		EmailValidation evalidate = new EmailValidation(registerEmail.getText());
		if (evalidate.validateEmail() == true) {
			System.out.println("true");
			e_mail = registerEmail.getText();
		} else {
			JOptionPane.showMessageDialog(null, "Your email format is invalid",
					null, JOptionPane.ERROR_MESSAGE);
		}
		String n_rc = registerNRC.getText();
		java.sql.Date birth_date = new java.sql.Date(dobCombo.getDate()
				.getTime());
		// System.out.println("Birth date:::" + birth_date);
		String address = registerAddress.getText();
		String qual = registerQualification.getText();
		String uniName = registerUniversity.getText();
		String security_qest = registerSecurity.getText();

		if (!first_name.equals("") && !last_name.equals("")
				&& !user_name.equals("") && !father_name.equals("")
				&& !pass_word.equals("") && !phone_no.equals("")
				&& !gen_der.equals("") && !e_mail.equals("")
				&& !n_rc.equals("") && !birth_date.equals("")
				&& !address.equals("") && !qual.equals("")
				&& !uniName.equals("") && !security_qest.equals("")) {
			Employee e = new Employee(first_name, last_name, user_name,
					pass_word, father_name, phone_no, birth_date, n_rc,
					gen_der, address, e_mail, qual, uniName, security_qest);
			int emplId = e.addEmployee();

			try {
				if(path!=null){
					File f = new File(path);
					InputStream input = new FileInputStream(f);
					System.out.println("input"+input);
					EmployeeImage emplImage = new EmployeeImage(emplId,
							f.getName(), path, input);
					if (emplImage.getEmployeeImageById(emplId) != 0) {
						emplImage.deleteEmployeeImage(emplId);
					}
					emplImage.insertImageIntoDatabase(f);
				}
			} catch (FileNotFoundException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			this.setVisible(false);
			// String name=first_name+" "+last_name;
			AdminHome rh = new AdminHome(username);
			rh.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null,
					"Please fill completely Employee information", "Warning",
					JOptionPane.WARNING_MESSAGE);
		}

	}

	private void browseActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser file = new JFileChooser();
		file.setCurrentDirectory(new File(System.getProperty("user.home")));
		// filter the files
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"*.Images", "jpg", "gif", "png");
		file.addChoosableFileFilter(filter);
		int result = file.showSaveDialog(null);
		// if the user click on save in Jfilechooser
		if (result == JFileChooser.APPROVE_OPTION) {
			selectedFile = file.getSelectedFile();
			path = selectedFile.getAbsolutePath();
			profileImage.setIcon(ResizeImage(path));
		}
		// if the user click on save in Jfilechooser

		else if (result == JFileChooser.CANCEL_OPTION) {
			System.out.println("No File Select");
		}
	}

	// Methode to resize imageIcon with the same size of a Jlabel
	public ImageIcon ResizeImage(String ImagePath) {
		ImageIcon MyImage = new ImageIcon(ImagePath);
		Image img = MyImage.getImage();
		Image newImg = img.getScaledInstance(profileImage.getWidth(),
				profileImage.getHeight(), Image.SCALE_SMOOTH);
		// System.out.println("Profile Image::"+profileImage.getWidth());
		// System.out.println("Profile Height::"+profileImage.getHeight());
		ImageIcon image = new ImageIcon(newImg);
		return image;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddEmployeeHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddEmployeeHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddEmployeeHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddEmployeeHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddEmployeeHome().setVisible(true);
			}
		});
	}
}
