/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.admin;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

import view.employee.EmployeeDetailsForEmployeeHome;
import view.myapp.LoginMain;
import model.Employee;
import model.EmployeeImage;
import dao.DatabaseUtils;

/**
 *
 * @author Yuzana Zaw Zaw
 */
public class UpdateEmployeeHomeAdminView extends javax.swing.JFrame {

	/**
	 * Creates new form UpdateEmployeeHomeAdminView
	 */
	String username;
	DatabaseUtils conn = new DatabaseUtils();
	PreparedStatement pst = null;
	ResultSet rst = null;
	Employee empl = null;

	String emplId;
	String fName;
	String lName;
	String uName;
	String pass;
	String fatherName;
	String phno;
	String em;
	Date dob;
	String NRC;
	String GEN;
	String add;
	String qualification;
	String univerisityName;
	String sec;
	File selectedFile = null;
	String image_Path = null;
	String path = null;
	private javax.swing.ButtonGroup btnGroup;

	public UpdateEmployeeHomeAdminView() {
		initComponents();
	}
	public UpdateEmployeeHomeAdminView(String username) {
		this.username=username;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		empl = new Employee();
		EmployeeImage emplImage = new EmployeeImage();
		int employee_id = empl.getEmployeeIdByUserName(username);
		System.out.println("EMPLOYEE ID:::+" + employee_id);
		byte[] imageByte = emplImage.getImageFileById(employee_id);
		image_Path = emplImage.getImagePathById(employee_id);
		try {
			DatabaseUtils conn = new DatabaseUtils();
			conn.OpenConnection();
			String sql = "Select * from Employee where employee_id = '"
					+ employee_id + "'";
			rst = conn.GetData(sql);
			while (rst.next()) {
				System.out.println("employee name::"
						+ rst.getString("username"));
				emplId = rst.getString("employee_id");
				fName = rst.getString("first_name");
				lName = rst.getString("last_name");
				uName = rst.getString("username");
				fatherName = rst.getString("father_name");
				pass = rst.getString("password");
				phno = rst.getString("phone_no");
				em = rst.getString("email");
				dob = rst.getDate("birth_date");
				NRC = rst.getString("nrc");
				GEN = rst.getString("gender");
				add = rst.getString("address");
				qualification = rst.getString("qualification");
				univerisityName = rst.getString("university_name");
				sec = rst.getString("security_qest");
			}
			conn.CloseConnection();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e
					+ "\n getRecruiterById  Error");
		}

		kGradientPanel1 = new keeptoo.KGradientPanel();
		btnGroup = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		updatePassword = new javax.swing.JPasswordField();
		jLabel19 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		updateUniversity = new javax.swing.JTextField();
		jLabel33 = new javax.swing.JLabel();
		updatePhno = new javax.swing.JTextField();
		jLabel34 = new javax.swing.JLabel();
		updateAddress = new javax.swing.JTextField();
		uu = new javax.swing.JLabel();
		updateUsername = new javax.swing.JTextField();
		updateButton = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		updateEmail = new javax.swing.JTextField();
		checkMale = new javax.swing.JRadioButton();
		checkFemale = new javax.swing.JRadioButton();
		title = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		updateSecurity = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		updateQualification = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		xpanel = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		ypanel = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		updateFirstName1 = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		updateLastName = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		updateNRC = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		dobCombo = new com.toedter.calendar.JDateChooser();
		employeeIdlbl = new javax.swing.JLabel();
		updateIdTxt = new javax.swing.JTextField();
		title1 = new javax.swing.JLabel();
		fatherNameLbl = new javax.swing.JLabel();
		updateFatherName = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		browse = new javax.swing.JButton();
		profileImage = new javax.swing.JLabel();
		subMainPanel = new javax.swing.JPanel();
		jSeparator3 = new javax.swing.JSeparator();
		titleLbl = new javax.swing.JLabel();
		addEmployeeButton = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		addRecruiterButton = new javax.swing.JPanel();
		addRecruiterLbl = new javax.swing.JLabel();
		employeeDetailsButton = new javax.swing.JPanel();
		emplDetailsLbl = new javax.swing.JLabel();
		settingsButton = new javax.swing.JPanel();
		settingsLbl = new javax.swing.JLabel();
		logOutButton = new javax.swing.JPanel();
		logoutLbl = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		profileImage.setBackground(new java.awt.Color(204, 204, 204));
		profileImage.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
		profileImage.setForeground(new java.awt.Color(204, 204, 204));
		profileImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		profileImage.setBounds(10, 10, 670, 250);
		profileImage.setText("PROFILE IMAGE");

		if (imageByte != null) {
			Image img = Toolkit.getDefaultToolkit().createImage(imageByte);
			Image img2 = img.getScaledInstance(145, 126, Image.SCALE_SMOOTH);
			ImageIcon image = new ImageIcon(img2);
			profileImage.setIcon(image);
		}

		updateIdTxt.setText(emplId);
		updateIdTxt.setEditable(false);
		updateFirstName1.setText(fName);
		updateLastName.setText(lName);
		updateUsername.setText(uName);
		updateFatherName.setText(fatherName);
		updatePassword.setText(pass);
		updatePhno.setText(phno);
		updateEmail.setText(em);
		updateNRC.setText(NRC);
		dobCombo.setDate(dob);

		checkMale.setText("Male");
		checkFemale.setText("Female");

		btnGroup.add(checkMale);
		btnGroup.add(checkFemale);
		System.out.println("GEN:::" + GEN);
		if (GEN.equals("Male")) {
			checkMale.setSelected(true);
		} else {
			checkFemale.setSelected(true);
		}
		updateQualification.setText(qualification);
		updateUniversity.setText(univerisityName);
		updateAddress.setText(add);
		updateSecurity.setText(sec);

		kGradientPanel1.setkEndColor(new java.awt.Color(102, 0, 153));
		kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
		kGradientPanel1.setMaximumSize(new java.awt.Dimension(2147483647,
				2147483647));
		kGradientPanel1.setMinimumSize(new java.awt.Dimension(1060, 270));
		kGradientPanel1.setPreferredSize(new java.awt.Dimension(1060, 646));
		kGradientPanel1.setLayout(null);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setForeground(new java.awt.Color(204, 204, 204));
		jPanel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(102, 102, 102));
		jLabel8.setText("Password");

		updatePassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updatePassword.setForeground(new java.awt.Color(102, 102, 102));
		updatePassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));
		jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(102, 102, 102));
		jLabel19.setText("Gender");

		jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel30.setForeground(new java.awt.Color(102, 102, 102));
		jLabel30.setText("What is your dream city?");

		updateUniversity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateUniversity.setForeground(new java.awt.Color(102, 102, 102));
		updateUniversity.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel33.setForeground(new java.awt.Color(102, 102, 102));
		jLabel33.setText("Phone No");

		updatePhno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updatePhno.setForeground(new java.awt.Color(102, 102, 102));
		updatePhno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0,
				2, 0, new java.awt.Color(12, 91, 160)));

		jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel34.setForeground(new java.awt.Color(102, 102, 102));
		jLabel34.setText("Email");

		updateAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateAddress.setForeground(new java.awt.Color(102, 102, 102));
		updateAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		uu.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		uu.setForeground(new java.awt.Color(102, 102, 102));
		uu.setText("Username");

		updateUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateUsername.setForeground(new java.awt.Color(102, 102, 102));
		updateUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		updateButton.setBackground(new java.awt.Color(0, 0, 51));
		updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				updateButtonMouseClicked(evt);
			}
		});
		updateButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(204, 204, 204));
		jLabel10.setText("EMAIL");
		updateButton.add(jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1,
						-1));

		jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(204, 204, 204));
		jLabel14.setText("Update");
		
		updateButton.add(jLabel14,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1,
						-1));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(102, 102, 102));
		jLabel1.setText("Address");

		updateEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateEmail.setForeground(new java.awt.Color(102, 102, 102));
		updateEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0,
				2, 0, new java.awt.Color(12, 91, 160)));

		checkMale.setText("Male");
		

		checkFemale.setText("Female");
		

		title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title.setText("Update Employee Profile");

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(102, 102, 102));
		jLabel4.setText("Qualification");

		updateSecurity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateSecurity.setForeground(new java.awt.Color(102, 102, 102));
		updateSecurity.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(102, 102, 102));
		jLabel5.setText("University Name");

		updateQualification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateQualification.setForeground(new java.awt.Color(102, 102, 102));
		updateQualification
				.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2,
						0, new java.awt.Color(12, 91, 160)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				title,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				245,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								updateQualification,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								288,
																								Short.MAX_VALUE)
																						.addComponent(
																								updateSecurity)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel4)
																														.addGroup(
																																jPanel1Layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																		.addComponent(
																																				updatePhno,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				278,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				updateUniversity,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				278,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				jLabel33)
																																		.addComponent(
																																				jLabel30)
																																		.addComponent(
																																				jLabel19)
																																		.addGroup(
																																				jPanel1Layout
																																						.createSequentialGroup()
																																						.addComponent(
																																								checkMale,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								59,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addComponent(
																																								checkFemale)))
																														.addComponent(
																																jLabel5))
																										.addGap(0,
																												0,
																												Short.MAX_VALUE)))
																		.addGap(37,
																				37,
																				37))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												updateUsername,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												278,
																												Short.MAX_VALUE)
																										.addComponent(
																												updatePassword)
																										.addComponent(
																												uu)
																										.addComponent(
																												jLabel8))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												updateEmail)
																										.addComponent(
																												updateAddress,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												278,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel34)
																										.addComponent(
																												jLabel1)))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												updateButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(115, 115, 115)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(title)
										.addGap(52, 52, 52)
										.addComponent(jLabel19)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(checkMale)
														.addComponent(
																checkFemale))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel30)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateSecurity,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateQualification,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												updateUniversity,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel33)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												updatePhno,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel34)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateEmail,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												updateAddress,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(uu)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateUsername,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel8)
										.addGap(18, 18, 18)
										.addComponent(
												updatePassword,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		kGradientPanel1.add(jPanel1);
		jPanel1.setBounds(750, 10, 390, 640);

		jPanel2.setOpaque(false);

		xpanel.setBackground(new java.awt.Color(0, 0, 51));
		xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xpanelMouseClicked(evt);
			}			
		});

		jLabel9.setBackground(new java.awt.Color(0, 0, 51));
		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel9.setText("X");

		javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(
				xpanel);
		xpanel.setLayout(xpanelLayout);
		xpanelLayout.setHorizontalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				xpanelLayout
						.createSequentialGroup()
						.addComponent(jLabel9,
								javax.swing.GroupLayout.DEFAULT_SIZE, 28,
								Short.MAX_VALUE).addContainerGap()));
		xpanelLayout.setVerticalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xpanelLayout
						.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(jLabel9,
								javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		ypanel.setBackground(new java.awt.Color(0, 0, 51));
		ypanel.setForeground(new java.awt.Color(0, 0, 51));
		ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ypanelMouseClicked(evt);
			}			
		});

		jLabel12.setBackground(new java.awt.Color(0, 0, 0));
		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("-");

		javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(
				ypanel);
		ypanel.setLayout(ypanelLayout);
		ypanelLayout.setHorizontalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel12)
						.addContainerGap()));
		ypanelLayout.setVerticalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel12)));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout
						.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(ypanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(xpanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(19, 19, 19)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		kGradientPanel1.add(jPanel2);
		jPanel2.setBounds(1150, 10, 70, 30);

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));
		jPanel3.setForeground(new java.awt.Color(204, 204, 204));
		jPanel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N

		jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(102, 102, 102));
		jLabel7.setText("First Name");

		updateFirstName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateFirstName1.setForeground(new java.awt.Color(102, 102, 102));
		updateFirstName1.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(102, 102, 102));
		jLabel21.setText("Last Name");

		updateLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateLastName.setForeground(new java.awt.Color(102, 102, 102));
		updateLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0,
				0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel22.setForeground(new java.awt.Color(102, 102, 102));
		jLabel22.setText("NRC No");

		updateNRC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateNRC.setForeground(new java.awt.Color(102, 102, 102));
		updateNRC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0,
				2, 0, new java.awt.Color(12, 91, 160)));

		jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel24.setForeground(new java.awt.Color(102, 102, 102));
		jLabel24.setText("DOB");

		employeeIdlbl.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		employeeIdlbl.setForeground(new java.awt.Color(102, 102, 102));
		employeeIdlbl.setText("Employee Id");

		updateIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateIdTxt.setForeground(new java.awt.Color(102, 102, 102));
		updateIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0,
				2, 0, new java.awt.Color(12, 91, 160)));

		title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		title1.setText("Update Employee Profile");

		fatherNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		fatherNameLbl.setForeground(new java.awt.Color(102, 102, 102));
		fatherNameLbl.setText("Father Name");

		updateFatherName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		updateFatherName.setForeground(new java.awt.Color(102, 102, 102));
		updateFatherName.setBorder(javax.swing.BorderFactory.createMatteBorder(
				0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

		jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
		jLabel25.setText("Profile Image");

		browse.setText("BROWSE");
		browse.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				browseActionPerformed(evt);
			}
		});

		profileImage.setBackground(new java.awt.Color(204, 204, 204));
		profileImage.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
		profileImage.setForeground(new java.awt.Color(204, 204, 204));
		profileImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		profileImage.setText("PROFILE IMAGE");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(65, 65, 65)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				title1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				278,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								jLabel21,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								updateLastName,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								278,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel7,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel24,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								dobCombo,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								125,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								employeeIdlbl,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								updateIdTxt,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								updateFirstName1,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								fatherNameLbl,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								updateFatherName,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel22,
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								updateNRC,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								278,
																								Short.MAX_VALUE)
																						.addComponent(
																								profileImage,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								145,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel25)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												browse)))
																		.addContainerGap(
																				47,
																				Short.MAX_VALUE)))));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addComponent(title1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												profileImage,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												126,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(browse)
														.addComponent(jLabel25))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(employeeIdlbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												updateIdTxt,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												updateFirstName1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel21)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateLastName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(fatherNameLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												updateFatherName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel22)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												updateNRC,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel24)
										.addGap(18, 18, 18)
										.addComponent(
												dobCombo,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(58, Short.MAX_VALUE)));

		kGradientPanel1.add(jPanel3);
		jPanel3.setBounds(350, 10, 390, 640);

		subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

		titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(204, 204, 204));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("RM SYS");
		titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		addEmployeeButton.setBackground(new java.awt.Color(0, 0, 51));
		addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addEmployeeButtonMouseClicked(evt);
			}			
		});
		addEmployeeButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(240, 240, 240));
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setText("Add Employee");
		addEmployeeButton.add(jLabel6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310,
						30));

		addRecruiterButton.setBackground(new java.awt.Color(0, 0, 51));
		addRecruiterButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addRecruiterButtonMouseClicked(evt);
			}			
		});
		addRecruiterButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		addRecruiterLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		addRecruiterLbl.setForeground(new java.awt.Color(240, 240, 240));
		addRecruiterLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		addRecruiterLbl.setText("Add Recruiter");
		addRecruiterButton.add(addRecruiterLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310,
						30));

		employeeDetailsButton.setBackground(new java.awt.Color(0, 0, 51));
		employeeDetailsButton
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						employeeDetailsButtonMouseClicked(evt);
					}					
				});
		employeeDetailsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		emplDetailsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		emplDetailsLbl.setForeground(new java.awt.Color(240, 240, 240));
		emplDetailsLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		emplDetailsLbl.setText("Employee Details");
		employeeDetailsButton.add(emplDetailsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, 310,
						30));

		settingsButton.setBackground(new java.awt.Color(0, 0, 51));
		settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				settingsButtonMouseClicked(evt);
			}
		});
		settingsButton
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		settingsLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		settingsLbl.setForeground(new java.awt.Color(240, 240, 240));
		settingsLbl.setText("Settings");
		settingsButton.add(settingsLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		logOutButton.setBackground(new java.awt.Color(0, 0, 51));
		logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logOutButtonMouseClicked(evt);
			}		
		});
		logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
		logoutLbl.setText("Log Out");
		logOutButton.add(logoutLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(
				subMainPanel);
		subMainPanel.setLayout(subMainPanelLayout);
		subMainPanelLayout
				.setHorizontalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																titleLbl,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																257,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jSeparator3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																268,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				addEmployeeButton,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				337,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addComponent(
																addRecruiterButton,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																employeeDetailsButton,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																subMainPanelLayout
																		.createSequentialGroup()
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								logOutButton,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								settingsButton,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								337,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap()));
		subMainPanelLayout
				.setVerticalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(titleLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(129, 129, 129)
										.addComponent(
												addEmployeeButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addRecruiterButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												employeeDetailsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												settingsButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												172, Short.MAX_VALUE)
										.addComponent(
												logOutButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(32, 32, 32)));

		kGradientPanel1.add(subMainPanel);
		subMainPanel.setBounds(0, 0, 349, 650);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addGap(0, 18, Short.MAX_VALUE)
						.addComponent(kGradientPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 1244,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		setSize(new java.awt.Dimension(1262, 661));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {
		String first_name = updateFirstName1.getText();
		String last_name = updateLastName.getText();
		String user_name = updateUsername.getText();
		String father_name = updateFatherName.getText();
		String pass_word = updatePassword.getText();
		String phone_no = updatePhno.getText();
		String gen_der = checkMale.isSelected() ? "Male" : "Female";
		String e_mail = updateEmail.getText();
		String n_rc = updateNRC.getText();
		java.sql.Date birth_date = new java.sql.Date(dobCombo.getDate()
				.getTime());
		System.out.println("Birth date:::" + birth_date);
		String address = updateAddress.getText();
		String qual = updateQualification.getText();
		String uniName = updateUniversity.getText();
		String security_qest = updateSecurity.getText();

		int employee_id = Integer.parseInt(updateIdTxt.getText());
		try {
			if (path != null) {
				File f = new File(path);
				InputStream input = new FileInputStream(f);
				EmployeeImage emplImage = new EmployeeImage(employee_id,
						f.getName(), path, input);
				if (emplImage.getEmployeeImageById(employee_id) != 0) {
					emplImage.deleteEmployeeImage(employee_id);
				}
				emplImage.insertImageIntoDatabase(f);
			}
		} catch (FileNotFoundException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		Employee e = new Employee(first_name, last_name, user_name, pass_word,
				father_name, phone_no, birth_date, n_rc, gen_der, address,
				e_mail, qual, uniName, security_qest);
		e.updateEmployeeProfile(employee_id);
		this.setVisible(false);
		//String name = first_name + " " + last_name;
		AdminHome rh = new AdminHome(username);
		rh.setVisible(true);
	}

	private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setState(UpdateEmployeeHomeAdminView.ICONIFIED);
	}

	private void browseActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser file = new JFileChooser();
		file.setCurrentDirectory(new File(System.getProperty("user.home")));
		// filter the files
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
				"*.Images", "jpg", "gif", "png");
		file.addChoosableFileFilter(filter);
		int result = file.showSaveDialog(null);
		// if the user click on save in Jfilechooser
		if (result == JFileChooser.APPROVE_OPTION) {
			selectedFile = file.getSelectedFile();
			path = selectedFile.getAbsolutePath();
			profileImage.setIcon(ResizeImage(path));
		}
		// if the user click on save in Jfilechooser

		else if (result == JFileChooser.CANCEL_OPTION) {
			System.out.println("No File Select");
		}
	}

	private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddEmployeeHome av = new AddEmployeeHome(username);
		this.setVisible(false);
		av.setVisible(true);
	}

	private void addRecruiterButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AddRecruiterHome ban = new AddRecruiterHome(username);
		this.setVisible(false);
		ban.setVisible(true);
	}

	

	private void employeeDetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		EmployeeDetailsForEmployeeHome rh = new EmployeeDetailsForEmployeeHome(username);
		this.setVisible(false);
		rh.setVisible(true);
	}

	private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		AdminSettings as = new AdminSettings(username);
		this.setVisible(false);
		as.setVisible(true);
	}

	private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		LoginMain lm = new LoginMain();
		this.setVisible(false);
		lm.setVisible(true);
	}

	// Methode to resize imageIcon with the same size of a Jlabel
	public ImageIcon ResizeImage(String ImagePath) {
		ImageIcon MyImage = new ImageIcon(ImagePath);
		Image img = MyImage.getImage();
		Image newImg = img.getScaledInstance(profileImage.getWidth(),
				profileImage.getHeight(), Image.SCALE_SMOOTH);
		// System.out.println("Profile Image::"+profileImage.getWidth());
		// System.out.println("Profile Height::"+profileImage.getHeight());
		ImageIcon image = new ImageIcon(newImg);
		return image;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					UpdateEmployeeHomeAdminView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					UpdateEmployeeHomeAdminView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					UpdateEmployeeHomeAdminView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					UpdateEmployeeHomeAdminView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UpdateEmployeeHomeAdminView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel addEmployeeButton;
	private javax.swing.JPanel addRecruiterButton;
	private javax.swing.JLabel addRecruiterLbl;
	private javax.swing.JButton browse;
	private javax.swing.JRadioButton checkFemale;
	private javax.swing.JRadioButton checkMale;
	private com.toedter.calendar.JDateChooser dobCombo;
	private javax.swing.JLabel emplDetailsLbl;
	private javax.swing.JPanel employeeDetailsButton;
	private javax.swing.JLabel employeeIdlbl;
	private javax.swing.JLabel fatherNameLbl;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JSeparator jSeparator3;
	private keeptoo.KGradientPanel kGradientPanel1;
	private javax.swing.JPanel logOutButton;
	private javax.swing.JLabel logoutLbl;
	private javax.swing.JLabel profileImage;
	private javax.swing.JPanel updateButton;
	private javax.swing.JPanel settingsButton;
	private javax.swing.JLabel settingsLbl;
	private javax.swing.JPanel subMainPanel;
	private javax.swing.JLabel title;
	private javax.swing.JLabel title1;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JTextField updateAddress;
	private javax.swing.JTextField updateEmail;
	private javax.swing.JTextField updateFatherName;
	private javax.swing.JTextField updateFirstName1;
	private javax.swing.JTextField updateIdTxt;
	private javax.swing.JTextField updateLastName;
	private javax.swing.JTextField updateNRC;
	private javax.swing.JPasswordField updatePassword;
	private javax.swing.JTextField updatePhno;
	private javax.swing.JTextField updateQualification;
	private javax.swing.JTextField updateSecurity;
	private javax.swing.JTextField updateUniversity;
	private javax.swing.JTextField updateUsername;
	private javax.swing.JLabel uu;
	private javax.swing.JPanel xpanel;
	private javax.swing.JPanel ypanel;
	// End of variables declaration
}
