package view.recruiter;

import java.awt.Color;

import view.employee.EmployeeDetailsForEmployeeHome;
import view.myapp.LoginMain;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yuzana Zaw Zaw
 */
public class RecruiterHome extends javax.swing.JFrame {

	/**
	 * Creates new form RecruiterHome
	 */
	private String rName, username;
	// Variables declaration - do not modify
	private javax.swing.JLabel changePasswordLbl;
	private javax.swing.JPanel changePasswordPanel;
	private javax.swing.JLabel checkEmplDetailsLbk;
	private javax.swing.JPanel checkEmployeeDetailsPanel;
	private javax.swing.JLabel downEmplCvLbl;
	private javax.swing.JPanel downEmplCvPanel;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JPanel logOutButton;
	private javax.swing.JLabel logoutLbl;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JLabel recruiterRoomLabel;
	private javax.swing.JPanel recruiterRoomPanel;
	private javax.swing.JPanel subMainPanel;
	private javax.swing.JLabel titleLbl;
	private javax.swing.JLabel updateProfileLbl;
	private javax.swing.JPanel updateRecruiterProfilePanel;
	private javax.swing.JLabel welcomeLabel;
	private javax.swing.JTextField welcomeText;
	private javax.swing.JPanel xpanel;
	private javax.swing.JPanel xyPanel;
	private javax.swing.JPanel ypanel;

	// End of variables declaration
	public RecruiterHome() {
		initComponents();
	}

	public RecruiterHome(String id, String rName) {
		username = id;
		this.rName = rName;
		initComponents();
		welcomeText(rName);
	}

	public void welcomeText(String name) {
		welcomeText.setText(name);
		welcomeText.setEditable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		recruiterRoomPanel = new javax.swing.JPanel();
		recruiterRoomLabel = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();
		welcomeLabel = new javax.swing.JLabel();
		welcomeText = new javax.swing.JTextField();
		xyPanel = new javax.swing.JPanel();
		xpanel = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		ypanel = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		subMainPanel = new javax.swing.JPanel();
		jSeparator3 = new javax.swing.JSeparator();
		titleLbl = new javax.swing.JLabel();
		updateRecruiterProfilePanel = new javax.swing.JPanel();
		updateProfileLbl = new javax.swing.JLabel();
		checkEmployeeDetailsPanel = new javax.swing.JPanel();
		checkEmplDetailsLbk = new javax.swing.JLabel();
		downEmplCvPanel = new javax.swing.JPanel();
		downEmplCvLbl = new javax.swing.JLabel();
		changePasswordPanel = new javax.swing.JPanel();
		changePasswordLbl = new javax.swing.JLabel();
		logOutButton = new javax.swing.JPanel();
		logoutLbl = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		mainPanel.setBackground(new java.awt.Color(255, 255, 255));
		mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		recruiterRoomPanel.setBackground(new java.awt.Color(204, 204, 255));

		recruiterRoomLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		recruiterRoomLabel.setForeground(new java.awt.Color(255, 255, 255));
		recruiterRoomLabel.setText("Recruiter Room");

		jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

		welcomeLabel.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
		welcomeLabel.setText("Welcome");

		welcomeText.setBackground(new java.awt.Color(204, 204, 204));
		welcomeText.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
		welcomeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		welcomeText.setBorder(null);

		javax.swing.GroupLayout recruiterRoomPanelLayout = new javax.swing.GroupLayout(
				recruiterRoomPanel);
		recruiterRoomPanel.setLayout(recruiterRoomPanelLayout);
		recruiterRoomPanelLayout
				.setHorizontalGroup(recruiterRoomPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								recruiterRoomPanelLayout
										.createSequentialGroup()
										.addGap(23, 23, 23)
										.addGroup(
												recruiterRoomPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																recruiterRoomLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																421,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																recruiterRoomPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				welcomeLabel)
																		.addGap(77,
																				77,
																				77)
																		.addComponent(
																				welcomeText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				419,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(22, Short.MAX_VALUE))
						.addGroup(
								recruiterRoomPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												recruiterRoomPanelLayout
														.createSequentialGroup()
														.addGap(272, 272, 272)
														.addComponent(
																jSeparator2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																414,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addContainerGap(24,
																Short.MAX_VALUE))));
		recruiterRoomPanelLayout
				.setVerticalGroup(recruiterRoomPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								recruiterRoomPanelLayout
										.createSequentialGroup()
										.addGap(28, 28, 28)
										.addComponent(recruiterRoomLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												58, Short.MAX_VALUE)
										.addGroup(
												recruiterRoomPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																welcomeLabel)
														.addComponent(
																welcomeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																51,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(39, 39, 39))
						.addGroup(
								recruiterRoomPanelLayout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												recruiterRoomPanelLayout
														.createSequentialGroup()
														.addContainerGap(171,
																Short.MAX_VALUE)
														.addComponent(
																jSeparator2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																10,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(19, 19, 19))));

		mainPanel.add(recruiterRoomPanel,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 710,
						200));

		xyPanel.setOpaque(false);

		xpanel.setBackground(new java.awt.Color(255, 255, 255));
		xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				xpanelMouseClicked(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel7.setText("X");

		javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(
				xpanel);
		xpanel.setLayout(xpanelLayout);
		xpanelLayout.setHorizontalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xpanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel7)
						.addContainerGap()));
		xpanelLayout.setVerticalGroup(xpanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel7, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		ypanel.setBackground(new java.awt.Color(255, 255, 255));
		ypanel.setForeground(new java.awt.Color(255, 255, 255));
		ypanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				ypanelMouseClicked(evt);
			}
		});

		jLabel8.setBackground(new java.awt.Color(255, 255, 255));
		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel8.setText("-");

		javax.swing.GroupLayout ypanelLayout = new javax.swing.GroupLayout(
				ypanel);
		ypanel.setLayout(ypanelLayout);
		ypanelLayout.setHorizontalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout
						.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jLabel8)
						.addContainerGap()));
		ypanelLayout.setVerticalGroup(ypanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				ypanelLayout.createSequentialGroup()
						.addGap(0, 1, Short.MAX_VALUE).addComponent(jLabel8)));

		javax.swing.GroupLayout xyPanelLayout = new javax.swing.GroupLayout(
				xyPanel);
		xyPanel.setLayout(xyPanelLayout);
		xyPanelLayout.setHorizontalGroup(xyPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				xyPanelLayout
						.createSequentialGroup()
						.addGap(0, 37, Short.MAX_VALUE)
						.addComponent(ypanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(xpanel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		xyPanelLayout.setVerticalGroup(xyPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(xpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(ypanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		mainPanel.add(xyPanel,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1,
						-1));

		subMainPanel.setBackground(new java.awt.Color(102, 0, 153));

		titleLbl.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
		titleLbl.setForeground(new java.awt.Color(204, 204, 204));
		titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLbl.setText("RM SYS");
		titleLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		updateRecruiterProfilePanel.setBackground(new java.awt.Color(0, 0, 51));
		updateRecruiterProfilePanel
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						updateRecruiterProfilePanelMouseClicked(evt);
					}
				});
		updateRecruiterProfilePanel
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		updateProfileLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		updateProfileLbl.setForeground(new java.awt.Color(240, 240, 240));
		updateProfileLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		updateProfileLbl.setText("Update Profile");
		updateRecruiterProfilePanel.add(updateProfileLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		checkEmployeeDetailsPanel.setBackground(new java.awt.Color(0, 0, 51));
		checkEmployeeDetailsPanel
				.addMouseListener(new java.awt.event.MouseAdapter() {
					public void mouseClicked(java.awt.event.MouseEvent evt) {
						checkEmployeeDetailsPanelMouseClicked(evt);
					}
				});
		checkEmployeeDetailsPanel
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		checkEmplDetailsLbk.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		checkEmplDetailsLbk.setForeground(new java.awt.Color(240, 240, 240));
		checkEmplDetailsLbk
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		checkEmplDetailsLbk.setText("Check Employee Detail");
		checkEmployeeDetailsPanel.add(checkEmplDetailsLbk,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320,
						30));

		downEmplCvPanel.setBackground(new java.awt.Color(0, 0, 51));
		downEmplCvPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				downEmplCvPanelMouseClicked(evt);
			}
		});
		downEmplCvPanel
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		downEmplCvLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		downEmplCvLbl.setForeground(new java.awt.Color(240, 240, 240));
		downEmplCvLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		downEmplCvLbl.setText("Download Employee CV");
		downEmplCvPanel.add(downEmplCvLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 310,
						30));
		downEmplCvPanel.setVisible(false);
		changePasswordPanel.setBackground(new java.awt.Color(0, 0, 51));
		changePasswordPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				changePasswordPanelMouseClicked(evt);
			}
		});
		changePasswordPanel
				.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		changePasswordLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		changePasswordLbl.setForeground(new java.awt.Color(240, 240, 240));
		changePasswordLbl
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		changePasswordLbl.setText("Settings");
		changePasswordPanel.add(changePasswordLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310,
						30));

		logOutButton.setBackground(new java.awt.Color(0, 0, 51));
		logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				logOutButtonMouseClicked(evt);
			}
		});
		logOutButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		logoutLbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
		logoutLbl.setForeground(new java.awt.Color(240, 240, 240));
		logoutLbl.setText("Log Out");
		logOutButton.add(logoutLbl,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1,
						30));

		javax.swing.GroupLayout subMainPanelLayout = new javax.swing.GroupLayout(
				subMainPanel);
		subMainPanel.setLayout(subMainPanelLayout);
		subMainPanelLayout
				.setHorizontalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGroup(
												subMainPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								changePasswordPanel,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								logOutButton,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								331,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								subMainPanelLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												checkEmployeeDetailsPanel,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												downEmplCvPanel,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												331,
																												Short.MAX_VALUE)
																										.addComponent(
																												updateRecruiterProfilePanel,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))))
														.addGroup(
																subMainPanelLayout
																		.createSequentialGroup()
																		.addGap(46,
																				46,
																				46)
																		.addGroup(
																				subMainPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								titleLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								257,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jSeparator3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								268,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		subMainPanelLayout
				.setVerticalGroup(subMainPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								subMainPanelLayout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(titleLbl)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(129, 129, 129)
										.addComponent(
												updateRecruiterProfilePanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												checkEmployeeDetailsPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												downEmplCvPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												changePasswordPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												134, Short.MAX_VALUE)
										.addComponent(
												logOutButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(66, 66, 66)));

		mainPanel
				.add(subMainPanel,
						new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0,
								340, -1));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(mainPanel,
								javax.swing.GroupLayout.DEFAULT_SIZE, 1083,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(9, Short.MAX_VALUE)
						.addComponent(mainPanel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 632,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(14, 14, 14)));

		setSize(new java.awt.Dimension(1095, 655));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void ypanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setState(RecruiterHome.ICONIFIED);
	}

	private void updateRecruiterProfilePanelMouseClicked(
			java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		UpdateRecruiterHome av = new UpdateRecruiterHome(username);
		this.setVisible(false);
		av.setVisible(true);
	}

	private void checkEmployeeDetailsPanelMouseClicked(
			java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		EmployeeDetailsForRecruiterHome ed=new EmployeeDetailsForRecruiterHome(username); 
		this.setVisible(false);
		ed.setVisible(true);
	}

	private void downEmplCvPanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		/*
		 * RidesHistory rh=new RidesHistory(username); this.setVisible(false);
		 * rh.setVisible(true);
		 */
	}

	private void changePasswordPanelMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		RecruiterSettings as = new RecruiterSettings(username);
		this.setVisible(false);
		as.setVisible(true);
	}

	private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		LoginMain lm = new LoginMain();
		this.setVisible(false);
		lm.setVisible(true);
	}
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RecruiterHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RecruiterHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RecruiterHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RecruiterHome.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RecruiterHome().setVisible(true);
			}
		});
	}
}
